---
title: "RFA #40624 Equity Analysis"
output: 
  flexdashboard::flex_dashboard
params: 
  AppsThroughMonth: "2023-01-31"
  AppsCurrentMonth: "Jan 2023"
  Internal: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(dplyr)
library(kableExtra)
library(maps)
library(fontawesome)
library(flexdashboard)
library(leaflet)
library(tigris)
library(shiny)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()


```

# Tables Layout

## Column

### Table 1

```{r}
mtcars |>
  select(mpg, cyl) |>
  kbl() |>
  kable_styling(bootstrap_options = c("striped", "hover")) 
```

## Column

### Table 2

```{r}
mtcars |>
  select(mpg, cyl) |>
  kbl() |>
  kable_styling(bootstrap_options = c("striped", "hover")) 
```


## Column

### Table 1

```{r}
mtcars |>
  select(mpg, cyl) |>
  group_by(cyl) |>
  summarise(AvgMPG = mean(mpg)) |>
  kbl() |>
  kable_styling(bootstrap_options = c("striped", "hover")) 
```

### Table 2

```{r}
mtcars |>
  select(mpg, cyl) |>
  group_by(cyl) |>
  summarise(AvgMPG = mean(mpg)) |>
  kbl() |>
  kable_styling(bootstrap_options = c("striped", "hover")) 
```

### Table 3

```{r}
mtcars |>
  select(mpg, cyl) |>
  group_by(cyl) |>
  summarise(AvgMPG = mean(mpg)) |>
  kbl() |>
  kable_styling(bootstrap_options = c("striped", "hover")) 
```

